name: "Lucas Neves Pereira"
picture: "picture.jpg"
bio: "Software Engineer from Portugal living in Paris, France"
meta:
  lang: "en"
  description: "Software Engineer from Portugal living in Paris, France"
  title: "Lucas Neves Pereira"
  author: "lucasnp"
  siteUrl: "https://lucasnp.dev"
links:
  - name: "Github"
    url: "https://github.com/lucasnevespereira"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/lucasnevespereira/"
  - name: "Youtube"
    url: "https://www.youtube.com/c/lucaasnp"
  - name: "Twitter/X"
    url: "https://twitter.com/lucaasnp_"
  - name: "Dev.to"
    url: "https://dev.to/lucasnevespereira"
contact:
  email: "lnevespereira@proton.me"
  phone: ""
  buymeacoffee: "https://buymeacoffee.com/lucaasnp"
  cv: ""
  socials:
    - name: "github"
      url: "https://github.com/lucasnevespereira"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/lucasnevespereira/"
    - name: "youtube"
      url: "https://www.youtube.com/c/lucaasnp"
    - name: "twitter"
      url: "https://x.com/lucaasnp_"
    - name: "blog"
      url: "https://dev.to/lucasnevespereira"
theme: "minimal"
